version: "3"
services:
  app:
    depends_on:
      - 11-11-11-sql
    image: 11-11-11-backend:latest
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/usr/src/app/src
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./package.json:/usr/src/app/package.json
      - ./.swcrc:/usr/src/app/.swcrc
      - ./dev.sh:/usr/src/app/dev.sh
    # command: /bin/sh -c "./dev.sh"
    command: /bin/sh -c "node dist/app.js"
    networks:
      - network

  11-11-11-sql:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: development
      POSTGRES_DB: database
    command: -p 6030
    ports:
      - "6030:6030"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    networks:
      - network

networks:
  network:
    name: elfelfelf
    external: true
